version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"

  api:
    image: crn-api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CrnTechnicalAssessmentDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;